export const AWARD_SOURCES_2026 = {
  Oscars: 'https://www.oscars.org/oscars/ceremonies/2026',
  Emmys: 'https://www.televisionacademy.com/features/news/awards-news/78th-emmy-awards-release',
  'Golden Globes': 'https://goldenglobes.com/winners-nominees/',
  BAFTA: 'https://www.bafta.org/awards/film/',
  'Critics Choice': 'https://www.criticschoice.com/2026-cca-winners/',
}

export const AWARDS_2026 = [
  {
    name: 'Oscars',
    type: 'Movies',
    categories: [
      ['Best Picture', 'One Battle After Another', 'One Battle After Another'],
      ['Best Director', 'Paul Thomas Anderson · One Battle After Another', 'One Battle After Another'],
      ['Best Actor', 'Michael B. Jordan · Sinners', 'Sinners'],
      ['Best Actress', 'Jessie Buckley · Hamnet', 'Hamnet'],
      ['Best Supporting Actor', 'Sean Penn · One Battle After Another', 'One Battle After Another'],
      ['Best Supporting Actress', 'Amy Madigan · Weapons', 'Weapons'],
      ['Animated Feature Film', 'KPop Demon Hunters', 'KPop Demon Hunters'],
      ['Cinematography', 'Sinners · Autumn Durald Arkapaw', 'Sinners'],
      ['Original Screenplay', 'Sinners · Ryan Coogler', 'Sinners'],
      ['Adapted Screenplay', 'One Battle After Another · Paul Thomas Anderson', 'One Battle After Another'],
      ['Original Score', 'Sinners · Ludwig Göransson', 'Sinners'],
      ['Visual Effects', 'Avatar: Fire and Ash', 'Avatar: Fire and Ash'],
    ],
  },
  {
    name: 'Emmys',
    type: 'Series',
    categories: [
      ['Outstanding Drama Series', 'The Pitt', 'The Pitt'],
      ['Outstanding Lead Actor · Drama', 'Noah Wyle · The Pitt', 'The Pitt'],
      ['Outstanding Lead Actress · Drama', 'Rhea Seehorn · Pluribus', 'Pluribus'],
      ['Outstanding Comedy Series', "Widow's Bay", "Widow's Bay"],
      ['Outstanding Lead Actor · Comedy', "Matthew Rhys · Widow's Bay", "Widow's Bay"],
      ['Outstanding Lead Actress · Comedy', 'Jean Smart · Hacks', 'Hacks'],
      ['Outstanding Reality Competition Program', 'The Traitors', 'The Traitors'],
      ['Outstanding Variety Series', 'The Late Show with Stephen Colbert', 'The Late Show with Stephen Colbert'],
    ],
  },
  {
    name: 'Golden Globes',
    type: 'Movies + Series',
    categories: [
      ['Best Motion Picture · Drama', 'Hamnet', 'Hamnet'],
      ['Best Motion Picture · Musical or Comedy', 'One Battle After Another', 'One Battle After Another'],
      ['Best Motion Picture · Animated', 'KPop Demon Hunters', 'KPop Demon Hunters'],
      ['Best Motion Picture · Non-English Language', 'The Secret Agent', 'The Secret Agent'],
      ['Best TV Series · Drama', 'The Pitt', 'The Pitt'],
      ['Best TV Series · Musical or Comedy', 'The Studio', 'The Studio'],
      ['Best TV Actor · Drama', 'Noah Wyle · The Pitt', 'The Pitt'],
      ['Best TV Actress · Drama', 'Rhea Seehorn · Pluribus', 'Pluribus'],
      ['Best TV Actor · Musical or Comedy', 'Seth Rogen · The Studio', 'The Studio'],
      ['Best TV Actress · Musical or Comedy', 'Jean Smart · Hacks', 'Hacks'],
    ],
  },
  {
    name: 'BAFTA',
    type: 'Movies',
    categories: [
      ['Best Film', 'One Battle After Another', 'One Battle After Another'],
      ['Director', 'Paul Thomas Anderson · One Battle After Another', 'One Battle After Another'],
      ['Leading Actor', 'Robert Aramayo · I Swear', 'I Swear'],
      ['Leading Actress', 'Jessie Buckley · Hamnet', 'Hamnet'],
      ['Supporting Actor', 'Sean Penn · One Battle After Another', 'One Battle After Another'],
      ['Supporting Actress', 'Wunmi Mosaku · Sinners', 'Sinners'],
      ['Animated Film', 'Zootropolis 2', 'Zootropolis 2'],
      ['Outstanding British Film', 'Hamnet', 'Hamnet'],
      ['Original Screenplay', 'Ryan Coogler · Sinners', 'Sinners'],
      ['Sound', 'F1', 'F1'],
    ],
  },
  {
    name: 'Critics Choice',
    type: 'Movies + Series',
    categories: [
      ['Best Picture', 'One Battle After Another', 'One Battle After Another'],
      ['Best Actor', 'Timothée Chalamet · Marty Supreme', 'Marty Supreme'],
      ['Best Actress', 'Jessie Buckley · Hamnet', 'Hamnet'],
      ['Best Director', 'Paul Thomas Anderson · One Battle After Another', 'One Battle After Another'],
      ['Best Animated Feature', 'KPop Demon Hunters', 'KPop Demon Hunters'],
      ['Best Drama Series', 'The Pitt', 'The Pitt'],
      ['Best Actor · Drama Series', 'Noah Wyle · The Pitt', 'The Pitt'],
      ['Best Actress · Drama Series', 'Rhea Seehorn · Pluribus', 'Pluribus'],
      ['Best Comedy Series', 'The Studio', 'The Studio'],
      ['Best Limited Series', 'Adolescence', 'Adolescence'],
    ],
  },
]
